name: Bug Report
description: File a bug report
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: WindowAnchor Version
      description: What version are you running? (right-click tray icon → About)
      placeholder: "v1.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Windows Version
      options:
        - Windows 11 25H2
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 10 22H2
        - Windows 10 21H2
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is.
      placeholder: "When I restore my workspace, VS Code opens but the file isn't loaded..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Paste logs from %AppData%\\WindowAnchor\\app.log if available"
      render: shell