name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: input
    id: version
    attributes:
      label: WindowAnchor Version
      description: What version are you running? (optional)
      placeholder: "v1.1.0"

  - type: dropdown
    id: os
    attributes:
      label: Windows Version
      description: Which OS are you using?
      options:
        - Windows 11 25H2
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 10 22H2
        - Windows 10 21H2

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.